### ISSUE TITLE
type not found, thx.Strings

### ISSUE THREAD

**Issue by ghost** [fponticelli/thx.csv#1]
Using a fresh haxelib install of thx.csv (v 0.1.2) I get the following error from the import of thx.csv:

```
/usr/lib/haxe/lib/thx,csv/0,1,2/src/thx/csv/Dsv.hx:3: characters 0-18 : Type not found : thx.Strings
```

which cites the 'using thx.Strings' statement at the top of `Dsv.hx`.  

Looking at the haxelib.json for thx.csv I notice that no dependencies property is there. Should thx.csv depend on thx.core?

Edit: I just, of course, added a -lib thx.core to my compile options, but wondered still wonder if that dependency should be in the haxelib.json ?

**Comment by fponticelli** [comment]
It should. I will make it so. In the meanwhile just add it to your project.

**Comment by fponticelli** [comment]
New version released. Feel free to open a new issue if you find more problems.

**Comment by ghost** [comment]
Gnarly thanks!
